version: '3'
services:
#mssql docker
  poliklinika-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Poliklinika-123
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - poliklinikanet

  poliklinika-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:poliklinika=Server=poliklinika-sql,1433;Database=Poliklinika;User=sa;Password=poliklinika;ConnectRetryCount=0
    ports:
      - 5000:5050
    networks:
      - poliklinikanet
    links:
      - poliklinika-sql
    depends_on:
      - poliklinika-sql
      
networks:
  poliklinikanet:
    driver: bridge      